# Configuration file for TwinPeaks2018
---
num_particles: 100
mcmc_steps: 1000
thin: 100
num_threads: 8
depth: 500.0
rng_seed: "auto"           # Can be "auto" or a non-negative integer
switch_sampler_reps: 100   # Number of repetitions of switch sampling
