# Configuration file for TwinPeaks2018
---
num_particles: 10
mcmc_steps: 10000            # Average number of MCMC steps per iteration
variable_mcmc_steps: false   # Should the number of MCMC steps vary?
thin: 10
num_threads: 10
depth: 100.0
rng_seed: "auto"             # Can be "auto" or a non-negative integer
switch_sampler_reps: 1000    # Number of repetitions of switch sampling

