# Configuration file for TwinPeaks2018
---
num_particles: 10
mcmc_steps: 1000
num_threads: 1
depth: 70.0                # TODO: Implement "auto" option
rng_seed: "auto"           # Can be "auto" or a non-negative integer
switch_sampler_reps: 10000 # Number of repetitions if doing switch sampling
